output_format: mysql2

allow_tables:
  - rows

disallow_tables:
  - skip

# Simple output
destination:
  store: local
  path:  'test/fixtures'

# remote_s3: &shared_s3
#   store: S3
#   access_key_id: 'foo'
#   secret_access_key: 'bar'
#   path: 'fixtures'
#
# environments:
#   # remote DB -> S3 fixtures
#   admin:
#     # `input` will be supplied by `REMOTE_DB` environment variable
#     output: *shared_s3
#
#   # S3 -> local fixtures files
#   default:
#     source: *shared_s3
#     destination:
#       store: local
#       path: 'test/fixtures'
