
allow_tables:
  - events
  - products
  - reports

disallow_tables:
  - users

output:
  store: local
  path:  'test/fixtures'

environments:
  admin:
    output:
      store: local
      path:  'test/fixtures'

